### PR TITLE
WIP: Sandbox area containing "unit test"-like scripts

### PR DESCRIPTION
**Pull request by bainbrid**
@mieskolainen please do not merge.

```
cd sandbox/brem
. run.sh
```

- Produces weights vs log(trk pt) and trk eta using KNN.
- Produces BDT using log(trk pt) and trk eta using both weighted and unweighted events
- BDT with unweighted events gives a ROC with AUC of ~80%
- BDT with weighted events gives a ROC with AUC of ~50%

### CODE REVIEW

**Comment by bainbrid** [comment]
@mieskolainen can we merge these standalone tests? do I need to rebase?

**Comment by bainbrid** [comment]
Terse slides slides [here](https://www.dropbox.com/scl/fi/rkpt3k2nwu0x2is9trp6d/240524_icenet_reweighting.pdf?rlkey=tv815lf9stc5uusghvpc44yoo&dl=0). Probably not totally self explanatory. Can discuss if needed.

**Comment by bainbrid** [comment]
@mieskolainen Let's chat on MM before we consider merging ...?

**Review by mieskolainen — APPROVED** [review]
ok

**Pull request merged**
